version: '2'

services:

  prosody-db:
    image: postgres
    container_name: prosody-db
    networks:
      - prosody
    environment:
      - POSTGRES_DB=prosody
      - POSTGRES_USER=prosody
      - POSTGRES_PASSWORD=prosody
    volumes:
      - prosody-db:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
      

  prosody:
    image: no-cloud.fr/maestro/prosody
    container_name: prosody
    networks:
      prosody:
        aliases:
          - prosody.components
      ldap:
        aliases:
          - prosody.ldap
      traefik:
        aliases:
          - prosody.traefik
    ports:
      - "5222:5222"
      - "5269:5269"
      - "5281:5281"
    volumes:
      - traefik_acme:/acme
    environment:
      - DOMAIN=bouts.me
      - LDAP_ADMIN_DN=cn=admin,dc=home
      - LDAP_ADMIN_PASSWORD=admin
    labels:
      - traefik.port=5280
      - traefik.frontend.entryPoints=http,https
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.rule=Host:xmpp.bouts.me
      - traefik.docker.network=traefik
    links:
      - prosody-db

  spectrum:
    image: no-cloud.fr/maestro/spectrum:latest
    container_name: spectrum
    networks:
      - prosody
    environment:
      - DOMAIN=bouts.me
      - PURPLE_UNSAFE_DEBUG=1
      - PURPLE_VERBOSE_DEBUG=1
    volumes:
      - prosody-data:/var/lib/spectrum2
    links:
      - prosody
      - prosody-db
    labels:
      - traefik.enable=false

volumes:
  prosody-data:
    driver: local
  prosody-db:
    driver: local
  traefik_acme:
    external: true

networks:
  prosody:
    driver: bridge
  ldap:
    external:
      name: ldap
  traefik:
    external:
      name: traefik
