version: '2'

services:

  maestro:
    image: no-cloud.fr/maestro:latest
    container_name: maestro
    restart: always
    working_dir: /
    networks:
      - ldap
      - traefik
    volumes_from:
      - maestro-gui
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - maestro:/maestro/services
    environment:
      - LDAP_HOST=ldap
      - LDAP_PORT=389
      - LDAP_ADMIN_DN=cn=admin,dc=home
      - LDAP_ADMIN_PASSWORD={{LDAP_ADMIN_PASSWORD}}
      - MAESTRO_DOMAIN={{MAESTRO_DOMAIN}}
    labels:
      - traefik.port=8888
      - traefik.frontend.rule=Host:maestro.{{MAESTRO_DOMAIN}}
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
      - traefik.docker.network=traefik

  maestro-gui:
    image: no-cloud.fr/maestro/gui:latest
    container_name: maestro-gui

  backup:
    image: no-cloud.fr/maestro/borg
    container_name: maestro-backup
    volumes_from:
      - maestro
    env_file:
      - ../backup.env
    environment:
      - SSHFS_REPO=maestro
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

volumes:
  data:
    driver: local
  maestro:
    external: true

networks:
  ldap:
    external:
      name: ldap
  traefik:
    external:
      name: traefik
