version: '2'

services:
  maestro:
    image: no-cloud.fr/maestro
    container_name: maestro
    networks:
      - ldap
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - maestro:/maestro/services
    environment:
      - LDAP_HOST=ldap
      - LDAP_PORT=389
      - LDAP_ADMIN_DN=cn=admin,dc=home
      - LDAP_ADMIN_PASSWORD={{LDAP_ADMIN_PASSWORD}}
      - MAESTRO_DOMAIN={{MAESTRO_DOMAIN}}
      - NOTIFY={{MAESTRO_NOTIFY}}
      - NOTIFY_JID={{MAESTRO_NOTIFY_JID}}
      - NOTIFY_PASSWORD={{MAESTRO_NOTIFY_PASSWORD}}
      - NOTIFY_TO={{MAESTRO_NOTIFY_TO}}
    labels:
      - traefik.port=5000
      - traefik.frontend.rule=Host:maestro.{{MAESTRO_DOMAIN}}
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
      - traefik.docker.network=traefik

  backup:
    image: no-cloud.fr/maestro/borg
    container_name: maestro-backup
    volumes:
      - maestro:/maestro
    environment:
      - SSHFS={{MAESTRO_SSHFS}}
      - SSHFS_PASSWORD={{MAESTRO_SSHFS_PASSWORD}}
      - BACKUP_DIRS=/maestro
      - EXTRACT_TO=/maestro/tmp
      - SSHFS_REPO=maestro
      - ARCHIVE_NAME=maestro
      - BORG_PASSPHRASE={{MAESTRO_BACKUP_PASSPHRASE}}
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
    security_opt:
      - apparmor:unconfined

networks:
  ldap:
    external: true
  traefik:
    external: true

volumes:
  maestro:
    external: true
