version: '2'

services:

  firefox:
    image: no-cloud.fr/maestro/firefox
    container_name: firefox
    shm_size: '2gb'
    networks:
      - guacamole
      - ldap
    volumes:
      - firefox-profile:/home
    environment:
      - LDAP_HOST=ldap
      - LDAP_BASE=ou=people,dc=home
      - LDAP_BIND_DN=cn=admin,dc=home
      - LDAP_BIND_PW=admin
      - LDAP_FILTER=(\&(objectClass=person)(memberof=cn=nextcloud,ou=groups,dc=home))

networks:
  guacamole:
    external:
      name: guacamole_guacamole
  ldap:
    external: true

volumes:
  firefox-profile:
    driver: local
