version: '3.5'

services:
  traefik:
    image: emilevauge/traefik
    container_name: traefik
    networks:
      - traefik
    ports:
      - 80:80
      - 443:443
    command:
#      - --loglevel=DEBUG
#      - --accesslog.filepath=/dev/stdout
      - --web=false
      - --docker
      - --docker.domain=domain.local
      - --acme=true
      - --acme.storage=/etc/traefik/acme/acme.json
      - --acme.entrypoint=https
      - --acme.ondemand=false
      - --acme.onhostrule=true
      - --acme.acmelogging=false
      - --entryPoints=Name:https Address::443 TLS
      - --entryPoints=Name:http Address::80 Redirect.EntryPoint:https
      - --defaultentrypoints=http,https
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - acme:/etc/traefik/acme
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"
    labels:
      - traefik.enable=false

  acme:
    image: no-cloud.fr/maestro/acme
    container_name: acme
    network_mode: "none"
    volumes:
      - acme:/acme
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"
    labels:
      - traefik.enable=false

volumes:
  acme:
    driver: local

networks:
  traefik:
    driver: bridge
    name: traefik
