version: '2'

services:

  firefox:
    image: no-cloud.fr/maestro/firefox
    container_name: firefox
    networks:
      - guacamole
      - ldap
    volumes:
      - firefox-profile:/home
    environment:
      - LDAP_HOST=ldap
      - LDAP_BASE=ou=people,dc=home
      - LDAP_BIND_DN={{LDAP_ADMIN_DN}}
      - LDAP_BIND_PW={{LDAP_ADMIN_PASSWORD}}
      - LDAP_FILTER=(\&(objectClass=person)(memberof=cn=nextcloud,ou=groups,dc=home))

networks:
  guacamole:
    external: true
  ldap:
    external: true

volumes:
  firefox-profile:
    driver: local
