version: '3.5'

services:

  ldap:
    image: no-cloud.fr/maestro/openldap
    container_name: ldap
    networks:
      - ldap
    environment:
      - LDAP_ORGANISATION=home
      - LDAP_DOMAIN=home
    volumes:
      - ldap:/var/lib/ldap
      - ldap:/etc/ldap/slapd.d
    logging:
      driver: json-file
      options:
        max-size: "2m"
        max-file: "5"
    labels:
      - traefik.enable=false

volumes:
  ldap:
    driver: local

networks:
  ldap:
    driver: bridge
    name: ldap
