version: '2'

services:

  nextcloud:
    image: no-cloud.fr/maestro/nextcloud
    container_name: nextcloud
    networks:
      - nextcloud
      - ldap
      - traefik
    links:
      - nextcloud-db
    environment:
      - DOMAIN=nextcloud.bouts.me
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=admin
      - LDAP_ADMIN_PASSWORD=admin
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
      - MYSQL_HOST=nextcloud-db
    volumes:
      - nextcloud:/var/www/html
      - nextcloud-data:/var/www/html/data
      - nextcloud-config:/var/www/html/config
      - nextcloud-apps:/var/www/html/custom_apps
      - media:/media
    labels:
      - traefik.port=80
      - traefik.frontend.rule=Host:nextcloud.bouts.me
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
      - traefik.docker.network=traefik

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: always
    networks:
      - nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=nextcloud
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=nextcloud
    labels:
      - traefik.enable=false

volumes:
  nextcloud:
    driver: local
  nextcloud-config:
    driver: local
  nextcloud-apps:
    driver: local
  nextcloud-data:
    driver: local
  nextcloud-db:
    driver: local
  media:
    external: true

networks:
  nextcloud:
    driver: bridge
  ldap:
    external:
      name: ldap
  traefik:
    external:
      name: traefik
