version: '2'

services:
  pyload:
    image: no-cloud.fr/maestro/pyload
    container_name: pyload
    networks:
      - traefik
      - guacamole
    ports:
      - 7227:7227
    volumes:
      - media:/media
    labels:
      - traefik.webinterface.port=8000
      - traefik.webinterface.frontend.rule=Host:pyload.bouts.me
      - traefik.webinterface.frontend.passHostHeader=true
      - traefik.webinterface.frontend.entryPoints=http,https

  filebot:
    image: rednoah/filebot:watcher
    container_name: filebot
    environment:
      - SETTLE_DOWN_TIME=60
    volumes:
      - media:/media
    command:
      - /media/Media/Downloads
      - --lang
      - fr
      - --output
      - /media/Media
      - --action
      - move
      - --def
      - movieFormat="Movies/{n}{' CD'+pi}{'.'+lang}"
      - seriesFormat="Series/{n.replaceTrailingBrackets()}/{episode.special ? 'Special':'Season '+s.pad(2)}/{n.replaceTrailingBrackets()} - {episode.special ? 'S00E'+special.pad(2):s00e00} - {t.replaceAll(/[!?.]+$$/).replaceAll(/[`´‘’ʻ]/, /'/).lowerTrail().replacePart(', Part $$1')}"
#      - seriesFormat="Series/{n}/{episode.special ? 'Special':'Season '+s.pad(2)}/{n} - {episode.special ? 'S00E'+special.pad(2):s00e00} - {t.replaceAll(/[`´‘’ʻ]/, /'/).replaceAll(/[!?.]+$$/).replacePart(', Part $$1')}{'.'+lang}"
      - artwork=n
      - clean=y

networks:
  traefik:
    external: true
  guacamole:
    external:
      name: guacamole_guacamole

volumes:
  media:
    external: true
