version: '2'

services:
  maestro:
    image: no-cloud.fr/maestro-python
    container_name: maestro-test
    networks:
      - ldap
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - maestro:/maestro/services
    environment:
      - LDAP_HOST=ldap
      - LDAP_PORT=389
      - LDAP_ADMIN_DN=cn=admin,dc=home
      - LDAP_ADMIN_PASSWORD={{LDAP_ADMIN_PASSWORD}}
      - MAESTRO_DOMAIN={{MAESTRO_DOMAIN}}
    labels:
      - traefik.port=5000
      - traefik.frontend.rule=Host:maestro.{{MAESTRO_DOMAIN}}
      - traefik.frontend.passHostHeader=true
      - traefik.frontend.entryPoints=http,https
      - traefik.docker.network=traefik

networks:
  ldap:
    external: true
  traefik:
    external: true

volumes:
  maestro:
    external: true
