version: '2'

services:

  maestro-updater:
    image: no-cloud.fr/maestro
    container_name: maestro-updater
    command:
      - --restart
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - maestro:/maestro/services

volumes:
  maestro:
    external: true
